image: markhobson/maven-chrome:jdk-11
stages:
  - test

cache:
  paths:
    - .m2/


test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/site/serenity/*
    reports:
      junit:
        - target/site/serenity/SERENITY-JUNIT-*.xml