image: maven:3.6.3-adoptopenjdk-15
stages:
  - test

cache:
  paths:
    - .m2/


test:
  stage: test
  script:
    - mvn clean surefire-report:report
  artifacts:
    when: always
    paths:
      - target/site/surefire-report.html
    reports:
      junit:
        - target/surefire-reports/*.xml