image: maven:3.6.3-adoptopenjdk-15
stages:
  - build
  - test

cache:
  paths:
    - .m2/


build:
  stage: build
  script: mvn compile -Dmaven.test.skip=true

test:
  stage: test
  script:
    - apt-get update
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.txt
      - target/surefire-reports/*.xml
    reports:
      junit:
        - target/surefire-reports/*.xml
  needs: ["build"]